/*
 * Copyright 2018-2020 NXP
 * This software is owned or controlled by NXP and may only be used strictly
 * in accordance with the applicable license terms.  By expressly accepting
 * such terms or by downloading, installing, activating and/or otherwise using
 * the software, you are agreeing that you have read, and that you agree to
 * comply with and are bound by, such license terms.  If you do not agree to
 * be bound by the applicable license terms, then you may not retain, install,
 * activate or otherwise use the software.
 */

/**
 * @file
 * This file provides vibration detection functionality by using an accelerometer sensor chip.
 *
 * @par vibration_algorithm
 *  The algorithm to detect vibration does not use a DFT or FFT, and is not looking at actual accelerometer sample data.
 *  Instead, it relies on the interrupts generated by the accelerometer to detect when a sample was above the
 *  threshold #ACCEL_VIBRATION_PARAMS_T.amplitude or below -#ACCEL_VIBRATION_PARAMS_T.amplitude. To get an estimate of the rate at
 *  which the excursions occur, the timespan #ACCEL_VIBRATION_PARAMS_T.duration is split in @c n chunks; and the number of
 *  received interrupts is counted in each chunk. To allow for lower sampling rates, a small number of chunks are
 *  allowed to have insufficient interrupts or 'hits'.
 *  When @c p% of the chunks, of which less than @c c are consecutive, have at least the required number of interrupts
 *  to reach #ACCEL_VIBRATION_PARAMS_T.frequency, a hit is reported to the application.
 *  - @c n - number of chunks
 *      Must be chosen such that each chunk should contain at least one hit. @n
 *      Setting it equal to #ACCEL_VIBRATION_PARAMS_T.frequency * #ACCEL_VIBRATION_PARAMS_T.duration is the absolute maximum number,
 *      giving just 1 expected interrupt per chunk.
 *      See #ACCEL_VIBRATION_HITS_PER_CHUNK
 *  - @c p - percentage of chunks with sufficient hits
 *      Higher ODR Output Data Rates - sampling rate on the accelerometer - have a big impact on current consumption.
 *      The chosen ODR #ACCEL_VIBRATION_ODR is too low to reliably catch all peaks. Requiring to have sufficient
 *      interrupts for all chunks will make it very hard to report any valid vibration. Lowering the threshold value
 *      helps in this regard, but also increases the likelihood of a false positive. Playing with this percentage is
 *      an alternative. In the implementation, a percentage not on chunks but on all expected hits is used.
 *      See #VIBRATION_HITTOLERATION
 *  - @c c - consecutive allowed number of misses
 *      When the chunk counts indicate too many expected interrupts have not been fired, it also indicates the vibration
 *      is no longer high enough or fast enough. The easiest approach to cover this is to choose @c n such that @c c
 *      interrupts are expected in each chunk. When a chunk has 0 hits reported, we can then reset the algorithm. When a
 *      chunk has more than 1 but less than @c c hits, we sum the difference, until the sum becomes too large to reach
 *      the @c p target. This will then also reset the algorithm.
 *      See #VIBRATION_CONSECUTIVEHITTOLERATION.
 */
#include "chip.h"
#include "accel.h"
#include "accel_internal.h"

#if ACCEL_VIBRATION_ENABLE

/**
 * The toleration on missing peak acceleration values.
 * For ease of calculation expressed in per-128-age.
 */
#define HITTOLERATION 121 /* 100*number/128 = % */

/**
 * The number of allowed acceleration peaks missed in succession due to the low chosen value of #ACCEL_VIBRATION_ODR.
 * @note This number is used indicatively only. The implementation only guarantees that the algorithm will be reset
 *  when one less than double this amount is missed.
 */
#define CONSECUTIVEHITTOLERATION 3

/** @c c - consecutive allowed number of misses - see @ref vibration_algorithm */
#define HITS_PER_CHUNK CONSECUTIVEHITTOLERATION

/** Groups all required data to detect vibrations. */
typedef struct VIBRATION_S {
    bool active; /**< Only when this equals @c true the other fields may be looked at. */

    /**
     * Counter indicating the total running duration of the ongoing vibration.
     * Always a positive value less than #ACCEL_VIBRATION_CHUNKS_COUNT.
     */
    unsigned int chunkNr;

    /**
     * Counting the number of 'hits', i.e. interrupts indicating a threshold excursion, in the current ongoing chunk.
     * Reset at the beginning of a new chunk.
     */
    unsigned int hits;

    /**
     * Sum of all the peaks we missed, assuming we're still monitoring a valid vibration pattern.
     * When this sum amounts to more than #ACCEL_VIBRATION_MAX_MISSES, we reset our detection logic.
     * @b Not reset at the beginning of a new chunk.
     */
    unsigned int misses;

    /**
     * @c n - number of chunks - see @ref vibration_algorithm
     * RO once written in #Accel_Vibration_SetParams
     */
    unsigned int chunksCount;

    /**
     * Number derived from @c p - percentage of chunks with sufficient hits - see @ref vibration_algorithm
     * RO once written in #Accel_Vibration_SetParams
     */
    unsigned int maxMisses;

    /**
     * Duration of one chunk, expressed in milliseconds.
     * RO once written in #Accel_Vibration_SetParams
     */
    unsigned int chunkDuration;

    /** A link */
    const ACCEL_VIBRATION_PARAMS_T * pParams;
} VIBRATION_T;

static VIBRATION_T sVibration;

/* ------------------------------------------------------------------------- */

bool Accel_Vibration_Start(void)
{
    sVibration.active = false; /* Started when the first interrupt arrives. */
    bool success = Accel_ProgramVibration(sVibration.pParams->amplitude);
    return success;
}

void Accel_Vibration_Stop(void)
{
    if (sVibration.active) {
        Accel_Cb(ACCEL_MODE_VIBRATION, ACCEL_STATE_FALSE);
        sVibration.active = false;
    }
}

void Accel_Vibration_SetParams(ACCEL_VIBRATION_PARAMS_T * pVibration)
{
    sVibration.pParams = pVibration;

    int hits = sVibration.pParams->duration * sVibration.pParams->frequency;
    sVibration.chunksCount = (unsigned int)(hits / HITS_PER_CHUNK);
    sVibration.maxMisses = (unsigned int)(hits * (128 - HITTOLERATION) / 128);
    sVibration.chunkDuration = (unsigned int)((1000 * HITS_PER_CHUNK) / sVibration.pParams->frequency);

    /* Example:
     *  duration = 4s (ACCEL_VIBRATION_DEFAULT_DURATION)
     *  frequency = 20Hz (ACCEL_VIBRATION_DEFAULT_FREQUENCY)
     * Gives:
     *  hits = 80
     *  chunksCount = 26 (with HITS_PER_CHUNK == 3)
     *  maxMisses = 4 (with HITTOLERATION == 121)
     *  chunkDuration = 150
     */
}

void Accel_Vibration_Detect(const ACCEL_INTERRUPT_STATUS_T status)
{
    if (sVibration.active && status.timerExpired) {
        sVibration.chunkNr++;
        if (sVibration.hits < HITS_PER_CHUNK) {
            sVibration.misses += HITS_PER_CHUNK - sVibration.hits;
        }
        if ((sVibration.hits == 0) || (sVibration.misses > sVibration.maxMisses)) {
            /* Too many misses. Reset the detection. */
            sVibration.active = false;
            /* Do not restart the timer. */
            Accel_Cb(ACCEL_MODE_VIBRATION, ACCEL_STATE_FALSE);
        }
        else if (sVibration.chunkNr >= sVibration.chunksCount) {
            /* A full detection has successfully finished, report this to the application and reset the detection. */
            sVibration.active = false;
            /* Do not restart the timer. */
            Accel_Cb(ACCEL_MODE_VIBRATION, ACCEL_STATE_END);
        }
        else { /* Continue the detection with the next chunk. */
            sVibration.hits = 0;
            /* sVibration.active remains true */
            Accel_TimerSet(ACCEL_VIBRATION_ODR, sVibration.chunkDuration);
        }
    }

    if (status.thresholdsExceeded) {
        if (!sVibration.active) {
            sVibration.chunkNr = 0;
            sVibration.hits = 0;
            sVibration.misses = 0;
            Accel_TimerSet(ACCEL_VIBRATION_ODR, sVibration.chunkDuration);
            sVibration.active = true;
            Accel_Cb(ACCEL_MODE_VIBRATION, ACCEL_STATE_BEGIN);
        }
        sVibration.hits++;
    }
}

#endif
