/*
 * Copyright 2018-2019 NXP
 * This software is owned or controlled by NXP and may only be used strictly
 * in accordance with the applicable license terms.  By expressly accepting
 * such terms or by downloading, installing, activating and/or otherwise using
 * the software, you are agreeing that you have read, and that you agree to
 * comply with and are bound by, such license terms.  If you do not agree to
 * be bound by the applicable license terms, then you may not retain, install,
 * activate or otherwise use the software.
 */

/**
 * @file
 * This module provides shake detection functionalities by using an accelerometer sensor chip.
 *
 * @par shake_algorithm
 *  A typical shake motion is unidirectional and involves a number of consecutive side to side shake movements of the
 *  device.
 *  Shaking as fast as possible produces ~5Hz waveform with peaks slightly above 4g. Normal shaking on the other
 *  hand produces typically 2 to 3 Hz (2 to 3 shakes per second).
 *  The following algorithm is used to detect the overall shake:
 *      Two interrupts will be generated by the chip on a single shake (one for going from one side to the other, and
 *      one for coming back). The interrupts will report opposite polarities such as X+/X- or Y-/Y+, etc. We can
 *      decide on shake event by counting opposite interrupts for a specified period.
 *      Note that we don't want to generate a shake event if the shakes occurs in a much shorter or longer time than
 *      expected. For example, a shock can produce 2 swings (shakes) in about 20ms, which is not to be reported as a
 *      shake event.
 */
#include <string.h>
#include "chip.h"
#include "accel.h"
#include "accel_internal.h"

#if ACCEL_SHAKE_ENABLE

typedef struct SHAKE_S {
    ACCEL_AXES_FLAGS_T last;
    int nrOfDetections;
    const ACCEL_SHAKE_PARAMS_T * pParams;
} SHAKE_T;

static SHAKE_T sShake;
static void ResetState(void);

/* ------------------------------------------------------------------------- */

static void ResetState(void)
{
    memset(&sShake.last, 0, sizeof(sShake.last));
    sShake.nrOfDetections = 0;
}

/* ------------------------------------------------------------------------- */

bool Accel_Shake_Start(void)
{
    ResetState();
    bool success = Accel_ProgramShake(sShake.pParams->amplitude);
    return success;
}

void Accel_Shake_Stop(void)
{
    if (sShake.nrOfDetections > 0) {
        Accel_Cb(ACCEL_MODE_SHAKE, ACCEL_STATE_FALSE);
        ResetState();
    }
}

void Accel_Shake_SetParams(ACCEL_SHAKE_PARAMS_T * pShake)
{
    sShake.pParams = pShake;
}

void Accel_Shake_Detect(const ACCEL_INTERRUPT_STATUS_T status)
{
    if (status.timerExpired) {
        /* End of shake process. Check if number of shakes are above threshold. */
        if (sShake.nrOfDetections >= sShake.pParams->count) {
            Accel_Cb(ACCEL_MODE_SHAKE, ACCEL_STATE_END);
        }
        else {
            Accel_Cb(ACCEL_MODE_SHAKE, ACCEL_STATE_FALSE);
        }
        ResetState();
    }

    if (status.thresholdsExceeded) {
        /* Check if at least one axis has alternated. */
        if ((sShake.last.x * status.flags.x < 0)
                || (sShake.last.y * status.flags.y < 0)
                || (sShake.last.z * status.flags.z < 0)) {
            if (sShake.nrOfDetections == 0) {
                Accel_TimerSet(ACCEL_SHAKE_ODR, sShake.pParams->duration);
                Accel_Cb(ACCEL_MODE_SHAKE, ACCEL_STATE_BEGIN);
            }
            sShake.nrOfDetections++;
        }

        /* Store the last state of each axis, but only when it was outside a threshold value. */
        if (status.flags.x) {
            sShake.last.x = status.flags.x;
        }
        if (status.flags.y) {
            sShake.last.y = status.flags.y;
        }
        if (status.flags.z) {
            sShake.last.z = status.flags.z;
        }
    }
}

#endif
