/*
 * Copyright 2018-2019 NXP
 * This software is owned or controlled by NXP and may only be used strictly
 * in accordance with the applicable license terms.  By expressly accepting
 * such terms or by downloading, installing, activating and/or otherwise using
 * the software, you are agreeing that you have read, and that you agree to
 * comply with and are bound by, such license terms.  If you do not agree to
 * be bound by the applicable license terms, then you may not retain, install,
 * activate or otherwise use the software.
 */

/**
 * @file
 * This file provides shock detection functionality by using an accelerometer sensor chip.
 *
 * @par shock_algorithm
 *  The algorithm to detect shocks relies solely on the interrupts generated by the accelerometer to detect when a
 *  sample was above the threshold #ACCEL_SHOCK_PARAMS_T.amplitude or below -#ACCEL_SHOCK_PARAMS_T.amplitude.
 *  To discriminate strong acceleration changes from real drops, a ...
 */
#include <string.h>
#include "chip.h"
#include "accel.h"
#include "accel_internal.h"

#if ACCEL_SHOCK_ENABLE

typedef enum SHOCK_STATE
{
    SHOCK_STATE_INIT, /**< Initial and reset state. No shock has been detected yet. */

    /**
     * A first high acceleration excursion has been detected. Algorithm is now idle, ignoring additional high
     * acceleration excursions until enough time has elapsed. See #ACCEL_SHOCK_RINGING_DURATION
     */
    SHOCK_STATE_FIRST,

    /**
     * Additional smaller acceleration peak(s) should follow after the initial high impact. In this state this
     * 'ringing' effect is check for. When detected, the whole acceleration process is considered a valid shock,
     * and reported to the application.
     */
    SHOCK_STATE_RINGING,
} SHOCK_STATE_T;

/** Groups all required data to detect shocks. */
typedef struct SHOCK_S {
    SHOCK_STATE_T state;

    /**
     * Counting the number of 'hits', i.e. interrupts indicating a threshold excursion, in the state
     * #SHOCK_STATE_RINGING.
     */
    int hits;

    const ACCEL_SHOCK_PARAMS_T * pParams;
} SHOCK_T;

static SHOCK_T sShock;

/* ------------------------------------------------------------------------- */

bool Accel_Shock_Start(void)
{
    sShock.state = SHOCK_STATE_INIT;
    bool success = Accel_ProgramShock(sShock.pParams->amplitude);
    return success;
}

void Accel_Shock_Stop(void)
{
    if (sShock.state != SHOCK_STATE_INIT) {
        Accel_Cb(ACCEL_MODE_VIBRATION, ACCEL_STATE_FALSE);
        sShock.state = SHOCK_STATE_INIT;
    }
}

void Accel_Shock_SetParams(ACCEL_SHOCK_PARAMS_T * pShock)
{
    sShock.pParams = pShock;
}

void Accel_Shock_Detect(const ACCEL_INTERRUPT_STATUS_T status)
{
    if (status.timerExpired) {
        switch (sShock.state) {
            case SHOCK_STATE_FIRST: /* Now try to detect the ringing effect */
                Accel_SetThresholds(sShock.pParams->ringingAmplitude);
                Accel_TimerSet(ACCEL_SHOCK_ODR, sShock.pParams->ringingDuration);
                sShock.hits = 0;
                sShock.state = SHOCK_STATE_RINGING;
                break;

            case SHOCK_STATE_RINGING:
                /* A full detection has finished, report this to the application and reset the detection. */
                Accel_Cb(ACCEL_MODE_SHOCK,
                         (sShock.hits >= sShock.pParams->ringingCount) ? ACCEL_STATE_END : ACCEL_STATE_FALSE);
                Accel_SetThresholds(sShock.pParams->amplitude);
                sShock.state = SHOCK_STATE_INIT;
                break;

            case SHOCK_STATE_INIT:
            default:
                /* May occur, if the timeout is very short and code execution has taken too long before the timer code
                 * could disable the watermark interrupt. Just ignore.
                 */
                break;
        }
    }

    if (status.thresholdsExceeded) {
        switch (sShock.state) {
            case SHOCK_STATE_INIT:
            default:
                Accel_TimerSet(ACCEL_SHOCK_ODR, sShock.pParams->waitTime);
                sShock.state = SHOCK_STATE_FIRST;
                Accel_Cb(ACCEL_MODE_SHOCK, ACCEL_STATE_BEGIN);
                break;

            case SHOCK_STATE_FIRST:
                /* Ignore additional shocks for now. */
                break;

            case SHOCK_STATE_RINGING:
                sShock.hits++;
                break;
        }
    }
}

#endif
