/*
 * Copyright 2018-2020 NXP
 * This software is owned or controlled by NXP and may only be used strictly
 * in accordance with the applicable license terms.  By expressly accepting
 * such terms or by downloading, installing, activating and/or otherwise using
 * the software, you are agreeing that you have read, and that you agree to
 * comply with and are bound by, such license terms.  If you do not agree to
 * be bound by the applicable license terms, then you may not retain, install,
 * activate or otherwise use the software.
 */

#ifndef __ACCEL_H_
#define __ACCEL_H_

#include <stdbool.h>
#include <stdint.h>
#include "accel/accel_dft.h"
#include "accel/accel_params.h"

/**
 * @defgroup MODS_NSS_ACCEL accel: Accelerometer sensor module
 * @ingroup MODS_NSS
 *
 * The accelerometer sensor module abstracts away an external accelerometer, and provides a high level API focusing
 * on event reporting of a specific type. The external accelerometer is to be connected with the NSH31xx IC via the HW
 * IC block.
 *
 * Four events can be detected, which are loosely defined as:
 * - @b shock: A sudden and big change in acceleration, in any direction.
 *  - Shocks last for a short amount of time, typically less than 20ms.
 *  - Shocks give rise of high accelerations, well above 16g.
 *  As an example, dropping a package from 1m or higher causes one or more shocks on impact to the floor.
 *  @n
 * - @b shake: A slow repetitive movement, typically human induced, where subsequent accelerations are detected in
 *  opposite directions.
 *  - Shakes last for a longer duration, where the full shake completes in a couple of seconds.
 *  - Shakes constitute a few medium accelerations that can amount to 8g.
 *  As an example: shaking a bottle to mix two fluids together.
 *  @n
 * - @b vibration: A fast repetitive movement, where small accelerations are detected over a longer period.
 *  In many cases vibration is unwanted. They can be caused by imbalances in rotating parts, by uneven friction, or by
 *  the meshing of gear teeth.
 *  - Vibrations last for a long duration, in the order of 10+ seconds.
 *  - Vibrations consist of a lot of small accelerations up to 4g.
 *  As an example: driving over cobblestones
 *  @n
 * - @b tilt: A change in orientation.
 *  Tilting is measured by using the force of gravity. It detects changes in how the gravity pulls to the object.
 *  It cannot be used to detect when an object is spun around the axis orthogonal to the earth's surface. @n
 *  As an example: a box is turned upside-down during transport.
 *
 * @note The module allows to change the type of the external accelerometer without affecting its API or functionality.
 *  The current supported external accelerometer sensors can be selected as a diversity setting.
 *  Given a type, some events may not be available. Also, not all events can be monitored for at the same time. See the
 *  diversity setting documentation for more details.
 *
 * @warning This module assumes it is the only block accessing the external accelerometer. Any other access through
 *  other unrelated code, both during, before or after the use of this module, may result in unpredictable behavior.
 *
 * @par Operation
 *  The module provides little information, if at all, about the actual x, y and z acceleration data points that lead up
 *  to the reporting of the event. A typical flow is:
 *  #- to configure the acceleration sensor. Depending on the type of event that is to be detected, a different
 *      configuration is applied.
 *  #- The accelerometer report threshold excesses via an interrupt line, which will wake up the ARM should the
 *      NHS31xx be in sleep, deep sleep or deep power down mode.
 *  #- Again depending on the type of events to be detected, a different algorithm is used by the accel module to
 *      conclude whether the interrupts generated by the acceleration sensor constitute a genuine event.
 *  #- Each event is reported via the callback function #Accel_Cb. It is defined weakly, allowing the application
 *      to override it, even when they are compiled in a different library. Only the end conclusion of the algorithm
 *      is reported; interrupt information and acceleration data points are lost to the application.
 *
 *  Physically, the shock, shake and vibration events are all variations on sudden changes in acceleration measurements;
 *  whereas tilting is about checking the gravity in a stable environment. The latter is a type of orientation, while
 *  The first three events are all types of motion, each requiring a different configuration of the same accelerometer.
 *  For this reason, it is only possible to detect either shock, shake or vibration; possibly combined with tilting.
 *
 * @anchor accelShock_anchor
 *  @par Detecting shocks
 *      Shocks are detected in a two-step process:
 *      - First a large shock is monitored for.
 *      - After the large shock, multiple smaller shocks are expected, in a so called 'ringing' effect.
 *      This leads to the following parameters:
 *      - amplitude: the minimal amplitude of the large shocks, and of the smaller shocks thereafter.
 *      - duration: the expected duration of the ringing effect.
 *      - count: combined with duration, indicates the rate at which the ringing effect is quenched.
 *      These can be configured here using #ACCEL_SHOCK_PARAMS_T.
 *
 * @anchor accelShake_anchor
 *  @par Detecting shakes
 *      A typical shake motion is unidirectional and involves a number of consecutive side to side shake movements of
 *      the device.
 *      Two interrupts will be generated by the chip on a single shake (one for going from one side to the other, and
 *      one for coming back). The interrupts will report opposite polarities such as X+/X- or Y-/Y+, etc. We can
 *      decide on the shake event by counting opposite interrupts for a specified period. @n
 *      Including the acceleration threshold fixed, this gives three configurable parameters:
 *      - duration: how long the user is expected to shake the product.
 *      - count: a minimum number of back=and-forth movements that are to be detected.
 *      - amplitude: the minimal amplitude of each swing (shake) before it is counted.
 *      These can be configured here using #ACCEL_SHAKE_PARAMS_T.
 *
 * @anchor accelVibration_anchor
 *  @par Detecting vibration
 *      Vibration is detected using a very simple algorithm, focusing on three components:
 *      - amplitude: an operating machine is typically already vibrating. Only when the vibrations are amplifying,
 *          a notification should be generated.
 *      - frequency: a low vibration frequency is usually not a concern. Higher frequencies exceeding the target
 *          amplitude, exert more force on the guarded product or machine and indicate an imminent failure or
 *          devaluation of the product's quality.
 *      - duration: typically, short bursts of vibration are not a concern. Only when vibration lasts for a long
 *          duration, a notification should be generated.
 *      These can be configured here using #ACCEL_VIBRATION_PARAMS_T.
 *
 * @anchor accelTilt_anchor
 *  @par Detecting tilting
 *      Tilting is fully determined by the accelerometer. Tilting will be reported when the stable absolute position
 *      of the accelerometer changes more than 45°, with a hysteresis angle of 15°.
 *      - Fixed values are used for both types of angles.
 *      - waitTime: the time after which a position is considered stable. Changes in angle shorter than this time are
 *          not reported.
 *      Configurable parameters are presented as #ACCEL_TILT_PARAMS_T.
 *
 * @par Diversity
 *  This module supports diversity, such as the choice between the supported accelerometer sensors. Some code space
 *  can be saved by stripping unused modes during pre-processing.
 *  Check @ref MODS_NSS_ACCEL_DFT for all diversity parameters.
 *
 * @note
 *  Accelerometer sensors have measurement scale range limits: usually they're capable of measuring acceleration
 *  up to 8g or 16g. This means a shock - which easily can produce very short bursts of 50g and higher - cannot be
 *  tracked very accurately: the higher acceleration values will be clipped.
 *
 *  @code
 *         ^                                               ^
 *        g|          X                                   g|
 *         |         XX                                    |
 *         |        X  XX                                  |
 *         |       X     XX                                |
 *       16+------XX------X-------------------------     16+------XXXXXXXXX------------------------
 *         |    XX        XX                               |    XX        XX
 *         |   XX          X                XX             |   XX          X                XX
 *         | XX             XX             X    time       | XX             XX             X   time
 *        0+---------------------------------------->     0+--------------------------------------->
 *         |                 XX          XX                |                 XX          XX
 *         |                  XX        XX                 |                  XX        XX
 *         |                    XX     XX                  |                    XX     XX
 *      -16+----------------------XX---X------------    -16+----------------------XXXXXX-----------
 *         |                       XX X                    |
 *         |                         XX                    |
 *         | Actual acceleration     X                     | Measured acceleration
 *  @endcode
 *
 * @{
 */

/**
 * The different modes which can be enabled. Each mode enables the detection of a specific type of acceleration.
 * @note Not all modes can be enabled at a time. The allowed combinations are restricted by the implementation and
 *  the choice of acceleration sensor.
 */
typedef enum ACCEL_MODE {
    ACCEL_MODE_NONE = 0, /**< No detection. */

    ACCEL_MODE_SHOCK = 0x01, /**< Detect shocks. See @ref accelShock_anchor */
    ACCEL_MODE_SHAKE = 0x02, /**< Detect human shake movements. See @ref accelShake_anchor */
    ACCEL_MODE_VIBRATION = 0x04, /**< Detect vibration. See @ref accelVibration_anchor */
    ACCEL_MODE_TILT = 0x08, /**< Detect tilting. See s@ref accelTilt_anchor */

    /** Number of modes. Not to be used as a possible mode. Use this in for loops or to define array sizes. */
    ACCEL_MODE_COUNT = 4,

    ACCEL_MODE_ALL = 0x0F, /**< Convenience value to target all acceleration modes at once. */
} ACCEL_MODE_T;

/**
 * Lists the different states that the algorithm detection of a mode is in, as reported via #Accel_Cb.
 */
typedef enum ACCEL_STATE {
    /**
     * A first interrupt has been received that could lead to a valid detection of a mode.
     * @warning Deinitializing the acceleration module through #Accel_DeInit, or going to the Deep power down or
     *  Power-off mode, will prevent further analysis, and the detection will not be completed.
     */
    ACCEL_STATE_BEGIN,

    /**
     * The algorithm as implemented by the acceleration module has finished the detection sequence of a mode, and has
     * concluded it was a false positive. The mode was @b not detected at this time.
     * @note Deinitializing the acceleration module through #Accel_DeInit, and thereafter going to the Deep power down
     *  or Power-off mode, can now take place, and will not will prevent future detections.
     */
    ACCEL_STATE_FALSE,

    /**
     * The algorithm as implemented by the acceleration module has finished a valid detection of a mode. The mode
     * was just now successfully detected.
     * @note Deinitializing the acceleration module through #Accel_DeInit, and thereafter going to the Deep power down
     *  or Power-off mode, can now take place, and will not will prevent future detections.
     */
    ACCEL_STATE_END
} ACCEL_STATE_T;

/**
 * Size of the workspace in use by this module. Defines the size of the array to pass along when calling #Accel_Init.
 */
#define ACCEL_WORKSPACE_SIZE 22

/* ------------------------------------------------------------------------- */

/** Default value for #ACCEL_SHOCK_PARAMS_T.amplitude when custom values are not given. */
#define ACCEL_SHOCK_DEFAULT_AMPLITUDE 12000 /* milli-g */

/** Default value for #ACCEL_SHOCK_PARAMS_T.waitTime when custom values are not given. */
#define ACCEL_SHOCK_DEFAULT_WAITTIME 100 /* ms */

/** Default value for #ACCEL_SHOCK_PARAMS_T.ringingAmplitude when custom values are not given. */
#define ACCEL_SHOCK_DEFAULT_RINGING_AMPLITUDE 4000 /* milli-g */

/** Default value for #ACCEL_SHOCK_PARAMS_T.ringingCount when custom values are not given. */
#define ACCEL_SHOCK_DEFAULT_RINGING_COUNT 2

/** Default value for #ACCEL_SHOCK_PARAMS_T.ringingDuration when custom values are not given. */
#define ACCEL_SHOCK_DEFAULT_RINGING_DURATION 900 /* ms */

/** Default value for #ACCEL_SHAKE_PARAMS_T.amplitude when custom values are not given. */
#define ACCEL_SHAKE_DEFAULT_AMPLITUDE 2500 /* milli-g */

/** Default value for #ACCEL_SHAKE_PARAMS_T.count when custom values are not given. */
#define ACCEL_SHAKE_DEFAULT_COUNT 4

/** Default value for #ACCEL_SHAKE_PARAMS_T.duration when custom values are not given. */
#define ACCEL_SHAKE_DEFAULT_DURATION 1500 /* ms */

/** Default value for #ACCEL_VIBRATION_PARAMS_T.amplitude when custom values are not given. */
#define ACCEL_VIBRATION_DEFAULT_AMPLITUDE 1500 /* milli-g */

/** Default value for #ACCEL_VIBRATION_PARAMS_T.frequency when custom values are not given. */
#define ACCEL_VIBRATION_DEFAULT_FREQUENCY 20 /* Hz */

/** Default value for #ACCEL_VIBRATION_PARAMS_T.duration when custom values are not given. */
#define ACCEL_VIBRATION_DEFAULT_DURATION 4 /* s */

/** Default value for #ACCEL_TILT_PARAMS_T.waitTime when custom values are not given. */
#define ACCEL_TILT_DEFAULT_WAITTIME 1000 /* ms */

/* ------------------------------------------------------------------------- */

/**
 * Weak declaration of the acceleration callback function. Override this in your application to capture all algorithm
 * state changes of the enabled modes.
 * @param mode : Reports the mode whose algorithm was triggered.
 * @param state : Reports what the current state is of the current algorithm running for the given mode.
 * @warning The application must redefine this to receive updates about the mode detection process.
 */
WEAK void Accel_Cb(ACCEL_MODE_T mode, ACCEL_STATE_T state);

/**
 * Initialization function. Initializes file scoped variables.
 * @pre Must be the first function called in this module.
 * @param pWorkspace Points to a contiguous array of #ACCEL_WORKSPACE_SIZE bytes free to be used by the validation
 *  process. Any change to this value is assumed to be stored in EEPROM before going to Deep Power Down mode and
 *  given back unaltered in a next call to this function.
 *  This allows the validation process to keep track of its own internal state.
 * @pre All calls to this function @b must provide the same workspace.
 * @pre The very first call to this function must provide a zero-initialized workspace.
 * @warning @c pWorkspace may not be @c NULL.
 * @note The HW I2C bus is not used during this call.
 */
void Accel_Init(void * pWorkspace);

/**
 * De-Init function.
 * @warning This call can still change the contents pointed to by @c pWorkspace (see #Accel_Init).
 * This must be the last function called in this module.
 * @note The HW I2C bus is not used during this call.
 */
void Accel_DeInit(void);

/**
 * Initialization function, continued. Initializes detection parameters.
 * @pre If called at all, must be the @b second function called in this module, @b after #Accel_Init,
 *  @b before Accel_Start.
 * @param pShock May be @c NULL. In that case, default values are set. Use this to forget and reset the parameters.
 * @param pShake May be @c NULL. In that case, default values are set. Use this to forget and reset the parameters.
 * @param pVibration May be @c NULL. In that case, default values are set. Use this to forget and reset the parameters.
 * @param pTilt May be @c NULL. In that case, default values are set. Use this to forget and reset the parameters.
 * @post New parameters are stored and will be used for @b all subsequent acceleration modes, including new detection
 *  sessions that are started after a power-off.
 * @note The HW I2C bus is not used during this call.
 */
void Accel_SetParams(const ACCEL_SHOCK_PARAMS_T * pShock, const ACCEL_SHAKE_PARAMS_T * pShake,
                     const ACCEL_VIBRATION_PARAMS_T * pVibration, const ACCEL_TILT_PARAMS_T * pTilt);

/**
 * Retrieves a copy of the current known configuration.
 * @param pShock May be @c NULL.
 * @param pShake May be @c NULL.
 * @param pVibration May be @c NULL.
 * @param pTilt May be @c NULL.
 * @note The HW I2C bus is not used during this call.
 */
void Accel_GetParams(ACCEL_SHOCK_PARAMS_T * pShock, ACCEL_SHAKE_PARAMS_T * pShake,
                     ACCEL_VIBRATION_PARAMS_T * pVibration, ACCEL_TILT_PARAMS_T * pTilt);

/**
 * Enables the detection of a mode. The modes given are merged with the already enabled modes. Modes that are already
 * enabled and also given here remain untouched.
 * @param mode : bitmask. An OR'd combination of enumeration values #ACCEL_MODE_T, which must be detected.
 * @return All modes that are currently enabled. @n
 *  For all enabled modes, the findings will be reported through #Accel_Cb
 * @pre #Accel_Init and #Accel_Start must have been called beforehand.
 * @pre The acceleration chip must be powered.
 * @note Not all modes can be enabled at a time. The allowed combinations are restricted by the implementation and
 *  the choice of acceleration sensor.
 * @pre The I2C driver is not in use: #Chip_I2C_Init has not yet been called, or #Chip_I2C_DeInit was the last call to
 *  this driver.
 * @post The I2C driver is no longer in use by the acceleration module.
 */
int Accel_Start(int mode);

/**
 * Disables the detection of a mode. Modes that already disabled remain disabled.
 * @param mode : bitmask. An OR'd combination of enumeration values #ACCEL_MODE_T, which no longer need to be
 *  detected.
 * @pre The acceleration chip must be powered.
 * @return All modes that remain enabled. @n
 *  For all modes that are still enabled, the findings will continue to be reported through #Accel_Cb
 * @pre The I2C driver is not in use: #Chip_I2C_Init has not yet been called, or #Chip_I2C_DeInit was the last call to
 *  this driver.
 * @post The I2C driver is no longer in use by the acceleration module.
 */
int Accel_Stop(int mode);

/**
 * The external accelerometer typically pulls/toggles a pin, provoking an interrupt. The application can use that as a
 * trigger to call this function, which queries the accelerometer and checks the enables modes.
 * @return True if the accelerometer had something to report, false otherwise.
 * @note This call requires the use of the I2C HW
 * @pre The I2C driver is not in use: #Chip_I2C_Init has not yet been called, or #Chip_I2C_DeInit was the last call to
 *  this driver.
 * @post The I2C driver is no longer in use by the acceleration module.
 */
bool Accel_Check(void);

#endif /** @} */
